import 'package:comment_tree/widgets/comment_child_widget.dart';

class Data {
  int sendPost = 0;

  List<bool> isLiked = [false, false, false];
  List<bool> isCommentLiked = [false, false, false];
  List<List<bool>> isSubCommnetLiked = [
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
    [
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false,
      false
    ],
  ];
  List<List<int>> subCommnetLikedCount = [
    [
      1,
      2,
      0,
      12,
      3,
      13,
      213,
      123,
      12,
      4,
      2,
      14,
      12,
      42,
      4,
      2,
      42,
      41,
      2,
      3,
      2321,
      314,
      4,
      53,
      5,
      35,
      32,
      23,
      24,
      324,
      234,
      32,
      432,
      4,
      523,
      532
    ],
    [
      0,
      1,
      5,
      1,
      2,
      0,
      12,
      3,
      13,
      213,
      123,
      12,
      4,
      2,
      14,
      12,
      42,
      4,
      2,
      42,
      41,
      2,
      3,
      2321,
      314,
      4,
      53,
      5,
      35,
      32,
      23,
      24,
      324,
      234,
      32,
      432,
      4,
      523,
      532
    ],
    [
      6,
      2,
      31,
      2,
      0,
      12,
      3,
      13,
      213,
      123,
      12,
      4,
      2,
      14,
      12,
      42,
      4,
      2,
      42,
      41,
      2,
      3,
      2321,
      314,
      4,
      53,
      5,
      35,
      32,
      23,
      24,
      324,
      234,
      32,
      432,
      4,
      523,
      532
    ],
  ];
  List<int> rootCommentLikeCount = [0, 2, 5];

  List<int> likeCount = [4, 8, 11];

  List<List<CommentChildWidget>> commentChild = [];

  List<String> comment = <String>[
    "It's a very complicated story. I'll tell you in short. I was best friends with this guy and he already had a girlfriend. I knew about it. It was long distance. He kept giving hopes about how he would break up with her as he has developed feelings for me now. I started developing feelings too. I had never felt like that with anyone like how I used to feel with him. I generally don't get attached to people. But I was SO attached. It's hard to explain. Then on and off he kept saying how once he'll break up with his gt, next month he's like he doesn't wont to break up, the month ofter, break up, again, no break up. So he kept doing this to me in a loop. I was really heartbroken. It was a complete mess. A lot more things happened. I just feel sometimes, that I shouldn't have made friends with him. I was isolated from all my other friends. I used to be with him 24x7. I just wonder at times how things would be differen of I weren't friends with him and hod other people. I'm fine now. No grudges, but it took a long time to get over it.",
    "What happened must have been a an emotional turmoil for you :( \nI can somewhat relata It takes a hell lot to break such patterns in life . ",
    "I have been with a similar guy doing his to me:'\nI 'snot been easy to get out this relationship.",
  ];
  List<List<String>> subComment = [
    [
      "It's a very complicated story. I'll tell you in short. I was best friends with this guy and he already had a girlfriend. I knew about it. It was long distance. He kept giving hopes about how he would break up with her as he has developed feelings for me now. I started developing feelings too. I had never felt like that with anyone like how I used to feel with him. I generally don't get attached to people. But I was SO attached. It's hard to explain. Then on and off he kept saying how once he'll break up with his gt, next month he's like he doesn't wont to break up, the month ofter, break up, again, no break up. So he kept doing this to me in a loop. I was really heartbroken. It was a complete mess. A lot more things happened. I just feel sometimes, that I shouldn't have made friends with him. I was isolated from all my other friends. I used to be with him 24x7. I just wonder at times how things would be differen of I weren't friends with him and hod other people. I'm fine now. No grudges, but it took a long time to get over it.",
      "What happened must have been a an emotional turmoil for you :( \nI can somewhat relata It takes a hell lot to break such patterns in life . ",
      "I have been with a similar guy doing his to me:'\nI 'snot been easy to get out this relationship.",
    ],
    [
      "It's a very complicated story. I'll tell you in short. I was best friends with this guy and he already had a girlfriend. I knew about it. It was long distance. He kept giving hopes about how he would break up with her as he has developed feelings for me now. I started developing feelings too. I had never felt like that with anyone like how I used to feel with him. I generally don't get attached to people. But I was SO attached. It's hard to explain. Then on and off he kept saying how once he'll break up with his gt, next month he's like he doesn't wont to break up, the month ofter, break up, again, no break up. So he kept doing this to me in a loop. I was really heartbroken. It was a complete mess. A lot more things happened. I just feel sometimes, that I shouldn't have made friends with him. I was isolated from all my other friends. I used to be with him 24x7. I just wonder at times how things would be differen of I weren't friends with him and hod other people. I'm fine now. No grudges, but it took a long time to get over it.",
      "What happened must have been a an emotional turmoil for you :( \nI can somewhat relata It takes a hell lot to break such patterns in life . ",
      "I have been with a similar guy doing his to me:'\nI 'snot been easy to get out this relationship.",
    ],
    [
      "It's a very complicated story. I'll tell you in short. I was best friends with this guy and he already had a girlfriend. I knew about it. It was long distance. He kept giving hopes about how he would break up with her as he has developed feelings for me now. I started developing feelings too. I had never felt like that with anyone like how I used to feel with him. I generally don't get attached to people. But I was SO attached. It's hard to explain. Then on and off he kept saying how once he'll break up with his gt, next month he's like he doesn't wont to break up, the month ofter, break up, again, no break up. So he kept doing this to me in a loop. I was really heartbroken. It was a complete mess. A lot more things happened. I just feel sometimes, that I shouldn't have made friends with him. I was isolated from all my other friends. I used to be with him 24x7. I just wonder at times how things would be differen of I weren't friends with him and hod other people. I'm fine now. No grudges, but it took a long time to get over it.",
      "What happened must have been a an emotional turmoil for you :( \nI can somewhat relata It takes a hell lot to break such patterns in life . ",
      "I have been with a similar guy doing his to me:'\nI 'snot been easy to get out this relationship.",
    ]
  ];
  List<List<String>> subCommentAvatar = [
    [
      'assert/images/avatar.png',
      'assert/images/av.jpg',
      'assert/images/av2.png',
    ],
    [
      'assert/images/avatar.png',
      'assert/images/av.jpg',
      'assert/images/av2.png',
    ],
    [
      'assert/images/avatar.png',
      'assert/images/av.jpg',
      'assert/images/av2.png',
    ]
  ];
  List<String> avatarIcon = [
    'assert/images/avatar.png',
    'assert/images/av.jpg',
    'assert/images/av2.png',
  ];
  List<String> img = [
    'assert/images/bg.jpg',
    'assert/images/bg1.jpg',
    'assert/images/bg2.jpg',
  ];
  List<String> headingText = [
    'Let out a thing of the past that bother you',
    'Talk About it',
    "Let's talk about it.",
  ];
  List<String> time = [
    '1 month',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '2 d',
    '3 month',
  ];
  List<String> totalComment = [
    '12',
    '9',
    '4',
  ];
}
